### ISSUE TITLE
Data Not Working

### ISSUE THREAD

**Issue by marciahon29** [armenak/DataDefender#101]
Please help me with the following error:

server:~/DataDefender-master/target$ /usr/local/jdk1.8.0/bin/java -jar D                                 ataDefender.jar database-discovery -d -r -R Requirement.xml

Creating lock file DataDefender.tmp
Locking file ...
Command-line arguments: [database-discovery, -d, -r, -R, Requirement.xml]
Connecting to database
Database vendor: mysql
Using driver com.mysql.jdbc.Driver
Database URL: jdbc:mysql://...:3306/...
Logging in using username nip
Loading database driver
Establishing database connection
Database vendor: mysql
Using driver com.mysql.jdbc.Driver
Database URL: jdbc:mysql://...:3306/...
Logging in using username nip
Loading database driver
Establishing database connection
Tables: [requirement.xml]
Data discovery in process
Probability threshold [0.55]
Model list [[name]]
********************************
Processing model name
********************************
Fetching table names from schema NIP
Table test
Analyzing table [test].[ORU_R01]
Analyzing table [test].[ORU_R01_xmlns]
...
...
List of suspects:
              Table*              Column*         Probability*               Mod                                 el*
Overall score: Undefined

Exception in thread "main" com.strider.datadefender.AnonymizerException: No matc                                 hes to create requirement from!
        at com.strider.datadefender.Discoverer.createRequirement(Discoverer.java                                 :53)
        at com.strider.datadefender.DataDefender.main(DataDefender.java:161)

**Comment by marciahon29** [comment]
I did: /usr/local/jdk1.8.0/bin/java -jar DataDefender.jar database-discovery -d -r

It produced a : Sample-Requirement.xml

My question is how to apply these changes to the database. I ran : /usr/local/jdk1.8.0/bin/java -jar DataDefender.jar database-discovery anonymize

Does this change anything?

**Comment by marciahon29** [comment]
I tried the above and I do not see any changes to the table.

**Comment by armenak** [comment]
@marciahon29 You will need to modify anonymizer.properties file and define Sample-Requirement.xml as a parameter.  Place anonymizer.properties file in the current directory and add the following:

requirement=/Users/strider/work/ubc/data_anonymization/cms/CMS-Requirement.xml

**Comment by armenak** [comment]
Closing this issue as there is no feedback from the user.
