### ISSUE TITLE
Need help while triggering the datadefender

### ISSUE THREAD

**Issue by Pranoy-Prabhakar** [armenak/DataDefender#102]
Hi Team 

I am getting below issue while triggering the data defender from cmd

C:\Project\DataDefender>java -jar DataDefender.jar database-discovery -c --data
C:\Project\DataDefender\db.properties --column-discovery C:\Project\DataDefender
\columndiscovery.properties -r -R columndiscovery
Creating lock file DataDefender.tmp
Locking file ...
Command-line arguments: [database-discovery, -c, --data, C:\Project\DataDefender
\db.properties, --column-discovery, C:\Project\DataDefender\columndiscovery.prop
erties, -r, -R, columndiscovery]
usage: DataAnonymizer anonymize|database-discovery|file-discovery|generate
                      [options] [table1 [table2 [...]]]
 -A,--anonymizer-properties <arg>       define anonymizer property file
 -c,--columns                           discover candidate column names
                                        for anonymization based on
                                        provided patterns
 -C,--column-properties <arg>           define column property file
 -d,--data                              discover candidate column for
                                        anonymization based on semantic
                                        algorithms
 -D,--data-properties <arg>             discover candidate column for
                                        anonymization based on semantic
                                        algorithms
 -debug                                 enable debug output
 -F,--file discovery properties <arg>   define file discovery property
                                        file
 -h,--help                              display help
 -P,--database properties <arg>         define database property file
 -r,--requirement                       create discover and create
                                        requirement file
 -R,--requirement-file                  define requirement file name
Exception in thread "main" java.lang.NullPointerException
        at com.strider.datadefender.DataDefender.main(DataDefender.java:78)
Closing lock file

I request you to help me to get it solved.

Kindly do let me know in case of more details.

Thanks and Regards
Pranoy Prabhakar

**Comment by armenak** [comment]
Hi Pranoy,

Instead of "--column-discovery" argument please use "--column-properties".

Regards,
Armenak

**Comment by Pranoy-Prabhakar** [comment]
Hi Armenak

Thanks for the response.
Yes it worked!!!

Now it can able to scan the fields but i guess i am not getting the output as expected.
I could see the scan is successful but its doesn't identify the sensitive field.
i have tried executing both data and column discovery.
Is it possible for you to guide me on this as may be i am missing something?

Thanks and Regards
Pranoy Prabhakar

**Comment by armenak** [comment]
Closing the issue as there is no response.
