### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException at com.strider.datadefender.DataDefender.main(DataDefender.java:78) 

### ISSUE THREAD

**Issue by ZINGYRAJEEV** [armenak/DataDefender#103]
Hi Developer.
We  have updated the DB.propertied file with db credentials details. 
We tried to use the DataDefender using below command but getting an null pointer execption
java -jar DataDefender.jar database-discovery -c --data C:\Users\X47609\DataDefender-master\target\classes\db.properties --column-discovery C:\Users\X47609\DataDefender-master\target\classes\columndiscovery.properties  [-r -R C:\Users\X47609\DataDefender-master\target\classes\requirement_output_file]

Could you please help in fixing this ?

**Comment by armenak** [comment]
Hello,

Try this:
java -jar DataDefender.jar database-discovery -c -C columndiscovery.properties -P db.properties 

The --data parameter is for data discovery, not for column discovery.

There is a bug related to creation of the requirement document. Please run the tool without -r and -R parameters. I will fix this issue in the next day or two.

**Comment by armenak** [comment]
Closing the issue as there is no response.
