### ISSUE TITLE
Verify if database-discovery works with Oracle 19c and ojdbc8.jar

### ISSUE THREAD

**Issue by term73** [armenak/DataDefender#122]
Hi,

Can you verify if database-discovery works with Oracle 19c and ojdbc8.jar.
My initial tests show that in https://github.com/armenak/DataDefender/blob/master/src/main/java/com/strider/datadefender/database/metadata/MetaData.java the getTableRS(md) does not get any result neither exception.

Thanks in advance.

**Comment by armenak** [comment]
Hello,

Unfortunately, I do not have access to Oracle 19c. I will see if I can download a free copy and test it out.

Thanks for reporting this.

**Comment by term73** [comment]
Hi,

I found some code snippet about the Oracle metadata related implementation which uses

import oracle.jdbc.OracleConnection;
import oracle.jdbc.OracleDatabaseMetaData;

Maybe we should consider using oracle.jdbc.OracleConnection and oracle.jdbc.OracleDatabaseMetaData ?

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;

import oracle.jdbc.OracleConnection;
import oracle.jdbc.OracleDatabaseMetaData;

public class MyMetaData extends OracleDatabaseMetaData {



    public MyMetaData(Connection conn) {
        super((OracleConnection) conn);
    }

    public synchronized ResultSet getTables(String catalog, String schemaPattern, String tableNamePattern, String[] types) throws SQLException {
        // catalog isn't used
        // dba view based sql  

        String sql = "SELECT NULL AS table_cat,"+
        "       o.owner AS table_schem,\n       "+
        "       o.object_name AS table_name,\n  "+
        "       o.object_type AS table_type,\n"+
        "       c.comments AS remarks\n" +
        "  FROM dba_objects o, dba_tab_comments c\n"+
        "  WHERE o.owner LIKE :1 ESCAPE '/'\n    "+
        "  AND o.object_name LIKE :2 ESCAPE '/'\n"+
        "  AND o.owner = c.owner (+)\n    "+
        "  AND o.object_name = c.table_name (+)\n";

        // bind params

         PreparedStatement stmt = connection.prepareStatement(sql);
         stmt.setString(1, schemaPattern == null ? "%" : schemaPattern);
         stmt.setString(2, tableNamePattern == null ? "%" : tableNamePattern);

        return stmt.executeQuery();
    }

    public static void main(String[] args) throws SQLException {

        String conString = "jdbc:oracle:thin:@//localhost:1521/xe";
        Properties props = new Properties();
        props.setProperty("user", "user");
        props.setProperty("password", "password");
        Connection conn = DriverManager.getConnection(conString, props);
        // use this class
        MyMetaData md = new MyMetaData(conn);

        // test it out
        ResultSet rset = md.getTables(null, "ORDS_METADATA", null, null);
            while (rset.next()) {
                System.out.println(rset.getString(2));
            }    

    }

}

best reagrds

**Comment by armenak** [comment]
I will try to find Oracle 19c this week and try it out. In the meantime, please feel free to create a branch and test tit out.

**Comment by armenak** [comment]
I just successfully run DataDefender using ojdbc8 driver. Can you please share your db.property file (without database password, of course).

**Comment by term73** [comment]
Hello,

Sorry about being late:

vendor=Oracle
driver=oracle.jdbc.OracleDriver
schema=my_dev
username=mydev_ks
password=xxxxx
url=jdbc:oracle:thin:@dev1.db.internal.xx:1521:dev1
skip-empty-tables=true

**Comment by armenak** [comment]
Sorry, but I am unable to reproduce this. I am successfully using the tool with Oracle 19c using ojdbc6 and ojdbc8.

**Comment by armenak** [comment]
Cannot reproduce.
