### ISSUE TITLE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project DataDefender: Fatal error compiling: invalid target release: 11 -> [Help 1]

### ISSUE THREAD

**Issue by christianorios** [armenak/DataDefender#184]
just trying to run maven package under my java version "11.0.16.1" 2022-08-18 LTS

**Comment by armenak** [comment]
This usually happens when Maven is using different version of Java. It is possible that you setup JAVA_HOME in the  mvn.bat or mvn.sh. Please check it out.

**Comment by christianorios** [comment]
Thanks, I've figured it out.

**Comment by DJsynther42** [comment]
> Thanks, I've figured it out.

I'm also having this error while trying to push my project onto Heroku. What did you do to fix yours?
