### ISSUE TITLE
Generate Requirement document based on data and column discovery process

### ISSUE THREAD

**Issue by armenak** [armenak/DataDefender#2]

**Comment by agithubusr** [comment]
Sample requirement file is now created in the discovery process with the -r and -R ${optional filename} cli options.  This is only a sample requirement file and will most likely require some modification before use (as a lot of the values are hard-coded), but it should create the tables and columns pretty much properly and should add pk attribute when only one pk and pkeys when there is a composite key.

Todo/known issues:
- hard-coded values (so should only be considered a template file); NB, column functions and parameters
- the column type currently only handles String types, other types will pass thru sql data type directly (which probably isn't what we want)
- documentation (coming soon...)

**Comment by armenak** [comment]
Done.
