### ISSUE TITLE
Document the way how to add MSSQL Server and Oracle JDBC drivers to local Maven repo

### ISSUE THREAD

**Issue by armenak** [armenak/DataDefender#25]
We can't have MSQL Server and Oracle JDBC drivers in this repo. It would be helpful to document step by step where to get the latest JDBC driver, how t oinclude them in local Maven repo and how to configure Maven build.

**Comment by agithubusr** [comment]
Added stuff to readme.  Hopefully it's descriptive enuff.

**Comment by armenak** [comment]
Thanks, Akira!

**Comment by armenak** [comment]
This task is completed.
