### ISSUE TITLE
DISTINCT keyword in MS SQL Server throws error

### ISSUE THREAD

**Issue by armenak** [armenak/DataDefender#27]

**Comment by zbateson** [comment]
If you can and you've not already worked on it, feel free to assign it to me.

**Comment by armenak** [comment]
That's fine, Zaahid. I will take care of this. If you have time, please look at the problem with columns/keys we saw on Thursday. 

Thanks,
Armenak

**Comment by armenak** [comment]
Issue was fixed.

**Comment by armenak** [comment]
This issue is fixed.
