### ISSUE TITLE
OutOfMemoryException with large MySQL table

### ISSUE THREAD

**Issue by zbateson** [armenak/DataDefender#45]
The default options for an RS using the MySQL driver stores the entire results of a query in memory when executeQuery is called.  Unfortunately for large tables this results in an OutOfMemoryException.

**Comment by armenak** [comment]
You may want to try batch_size=NNN property in anonymizer.properties file.

**Comment by zbateson** [comment]
That only helps with the update batch, this is an issue with loading data from a large table (executeQuery, not updateBatch).

I have a fix almost ready, just testing it :)
