### ISSUE TITLE
Ability to create an array of database/schema names and run through all of them

### ISSUE THREAD

**Issue by greenjuicy** [armenak/DataDefender#66]
• Ability to create an array of database/schema names and run through all of them. 

--> Add P2 batch file that calls batch file. (high) Dec 2nd P1

**Comment by armenak** [comment]
Currently, the tool is not supporting it. Moreover, I'd need to think whether I'd like to make this change as it may significantly complicate the architecture.

Quick-and-durty solution would to create a batch file such as below:

ECHO Processing Database N1
java -cp "DataDefender.jar;ojdbc6.jar" com.strider.datadefender.DataDefender database-discovery -c -P db1.properties > db1.columns.txt
java -cp "DataDefender.jar;ojdbc6.jar" com.strider.datadefender.DataDefender database-discovery -d -P db1.properties > db1.data.txt

ECHO Processing Database N2
java -cp "DataDefender.jar;ojdbc6.jar" com.strider.datadefender.DataDefender database-discovery -c -P db2.properties > db2.columns.txt
java -cp "DataDefender.jar;ojdbc6.jar" com.strider.datadefender.DataDefender database-discovery -d -P db2.properties > db2.data.txt

Here, we list all the databases we would like to scan and point to a different property files which define database connection parameters.

**Comment by armenak** [comment]
@greenjuicy Please verify and let me know if I can close this ticket.
