### ISSUE TITLE
Redirect output into a file

### ISSUE THREAD

**Issue by greenjuicy** [armenak/DataDefender#68]
• Generate report file(s) 

--> Dec 2nd P1

**Comment by armenak** [comment]
Sample batch file can help to achieve this. For example:

ECHO Processing Database N1
java -cp "DataDefender.jar;ojdbc6.jar" com.strider.datadefender.DataDefender database-discovery -c -P db1.properties > db1.columns.txt
java -cp "DataDefender.jar;ojdbc6.jar" com.strider.datadefender.DataDefender database-discovery -d -P db1.properties > db1.data.txt

ECHO Processing Database N2
java -cp "DataDefender.jar;ojdbc6.jar" com.strider.datadefender.DataDefender database-discovery -c -P db2.properties > db2.columns.txt

java -cp "DataDefender.jar;ojdbc6.jar" com.strider.datadefender.DataDefender database-discovery -d -P db2.properties > db2.data.txt

**Comment by armenak** [comment]
@greenjuicy Please verify and let me know if I can close this ticket.
