### ISSUE TITLE
Process high risk PI

### ISSUE THREAD

**Issue by greenjuicy** [armenak/DataDefender#71]
• Enable capability to configure what field types are considered in scope for discovery by machine learning  

--> P2 Jan

**Comment by armenak** [comment]
@greenjuicy I need some clarification about this issue. What do you mean by field types?

**Comment by armenak** [comment]
The list of high risk PI is below:
- SIN
- Biomedical
- Bank
- Passport
- Health ID
- Driver License
- Health information

**Comment by armenak** [comment]
Completed.
