### ISSUE TITLE
Define overall risk score per database or repository

### ISSUE THREAD

**Issue by greenjuicy** [armenak/DataDefender#73]
• Overall risk score per database/repository based on number of records per database e.g. 

--> P3

**Comment by armenak** [comment]
@greenjuicy I need some clarification here. The score should be based on some criteria. For now, I will create some configurable criteria for both column and data discovery.

**Comment by armenak** [comment]
Score is identified based on the number of rows in the table.

**Comment by armenak** [comment]
@greenjuicy Please verify.

**Comment by armenak** [comment]
As per agreement with client, closing this issue.
