### ISSUE TITLE
Only type of PI found is "name"

### ISSUE THREAD

**Issue by greenjuicy** [armenak/DataDefender#76]
• Also, looking at the data discovery, the only types of PI found is “Name”. I would expect other types to be found in this database. 

--> P1

**Comment by armenak** [comment]
In order to use other data mining models, datadiscovery.propertie file needs to be modified.

Currently, the following models are supported: person,location,date,time,money. They can be defined in "models" parameter and separated by comma:

models=person,location,date,time,money

**Comment by armenak** [comment]
@greenjuicy Please verify and let me know if I can close this ticket.
