### ISSUE TITLE
db.properties does not exists

### ISSUE THREAD

**Issue by blacksad77** [armenak/DataDefender#78]
src/main/resources/db.properties does not exists in repo.

**Comment by nmarasoiu** [comment]
No such file: src/main/resources/db.properties. So we don't know the format for this input. Any help on calling the DB column discovery?

**Comment by nmarasoiu** [comment]
To be more clear, the command:
java -jar DataDefender.jar database-discovery -c --data <db.properties> --column-discovery <columndiscovery.properties> [-r -R <requirement_output_file>]
It is unclear what example of a file to pass as db.properties (e.g. the names of the keys).

**Comment by armenak** [comment]
My bad, I did add db.property

**Comment by armenak** [comment]
My fault - I did not add db.properties file in the sample projects. 
Sample format for Oracle would be as follow:

vendor=oracle
driver=oracle.jdbc.driver.OracleDriver
schema=<schema_name>
username=<username>
password=<password>
url=jdbc:oracle:thin:@<host_name>:<port_number>:SID

**Comment by armenak** [comment]
@blacksad77 ping
