### ISSUE TITLE
ORA-00942 during analyzing sample data on Oracle

### ISSUE THREAD

**Issue by blacksad77** [armenak/DataDefender#79]
During column discovery on Oracle:
 Executing query against database: SELECT count(*)  FROM SCHEMA_NAME.TRANSACTIONS
**14:24:58 DEBUG - Executing query against database: SELECT MSISDN FROM TRANSACTIONS WHERE MSISDN IS NOT NULL  AND rownum <= 5
14:24:58 ERROR - java.sql.SQLSyntaxErrorException: ORA-00942**
:24:58 INFO - Column                     : TRANSACTIONS.MSISDN
14:24:58 INFO - =================================================
14:24:58 INFO - Number of rows in the table: 45352689
14:24:58 INFO - Score                      : High
14:24:58 INFO - Sample data
14:24:58 INFO - -----------
14:24:58 INFO - 
14:24:58 INFO - Overall score: Medium

Sampling data does not prefix tablename with schema name.

**Comment by armenak** [comment]
Please use sample db.properties file:
vendor=oracle
driver=oracle.jdbc.driver.OracleDriver
schema=<schema_name>
username=<user_name>
password=<user_password>
url=jdbc:oracle:thin:@<host_name>:<port_number>:SID

Schema name should be defined.

**Comment by armenak** [comment]
@blacksad77 did you have a chance to run the tool with db.properties file?

**Comment by blacksad77** [comment]
Yes, a while ago, a have looked into your code and guessed db.properties :-)

2017-06-26 20:37 GMT+02:00 Armenak Grigoryan <notifications@github.com>:

**Comment by armenak** [comment]
Great. I posted the example of db.properties file above. Please let me know if you run into issues.
