### ISSUE TITLE
MSSQL - Incorrect syntax near LIMIT

### ISSUE THREAD

**Issue by lcmarques** [armenak/DataDefender#80]
Some exceptions when using LIMIT in datadiscovery.properties for SQLServer (Azure SQLDatabase).

Analyzing table [Client]
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'LIMIT'.
Analyzing table [Client]
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'LIMIT'.

MSSQL doesn't support LIMIT keyword and it uses TOP instead.

Can you please help?

**Comment by lcmarques** [comment]
Here is the patch that you should apply, or at least review it.

[patch_sqlserver_limit.txt]
(https://github.com/armenak/DataDefender/files/1152302/patch_sqlserver_limit.txt)

**Comment by armenak** [comment]
I think this issue can be closed.
