### ISSUE TITLE
Issue - File Discovery

### ISSUE THREAD

**Issue by Abhishek0510** [armenak/DataDefender#90]
Hi,

Using File discovery,why it's not detecting all the PD data like all the name(only few specific name only getting detected),DOB and others ,I have attached the file and logs for your refrence.

Also i am unable to find any db.properties file in source code for Column discovery.

Thanks,
Abhishek
[testsample.txt](https://github.com/armenak/DataDefender/files/1799354/testsample.txt)
[anonymizer.log](https://github.com/armenak/DataDefender/files/1799356/anonymizer.log)

**Comment by armenak** [comment]
Hello Abhishek,

Sample of db.properties file is below:
vendor=mysql
schema=
driver=com.mysql.jdbc.Driver
username=<username>
password=<password>
url=jdbc:mysql://<host_name>:3306/<dbname>
skip-empty-tables=<true|false>

**Comment by armenak** [comment]
I will have a look at the issue with FileDiscovery, although this part is still in Beta testing.

**Comment by Abhishek0510** [comment]
Thanks.

**Comment by armenak** [comment]
@Abhishek0510  Can you please provide more specific example. What kind of data you have, what is your expected results. What are the formats of the files you have?

**Comment by armenak** [comment]
No respond. Closing the issue.
