### ISSUE TITLE
Data Discovery

### ISSUE THREAD

**Issue by marciahon29** [armenak/DataDefender#95]
Hello,

For Data Discovery, could we specify a table?

In the Anonymizer stage, we are allowed to specify a table.

Thanks,
Marcia

**Comment by armenak** [comment]
No, you can't specify the table in data discovery. However, you can specify that you want to skip empty tables in db.properties file. 

And in general, I would not suggest to exclude any database table from discovery process. Often databases, especially legacy databases, contain surprises.
