### ISSUE TITLE
Error - Locking File

### ISSUE THREAD

**Issue by marciahon29** [armenak/DataDefender#96]
Hello,

Please let me know what to do, I have the following error:

/DataDefender-master/target$ /usr/local/jdk1.8.0/bin/java -jar DataDefender.jar database-discovery -c --data ../             src/main/resources/db.properties --column-discovery ../src/main/resources/columndiscovery.properties
Creating lock file DataDefender.tmp
Locking file ...
Command-line arguments: [database-discovery, -c, --data, ../src/main/resources/db.properties, --column-discovery, ../src/main/re             sources/columndiscovery.properties]
usage: DataAnonymizer anonymize|database-discovery|file-discovery|generate
                      [options] [table1 [table2 [...]]]
 -A,--anonymizer-properties <arg>       define anonymizer property file
 -c,--columns                           discover candidate column names
                                        for anonymization based on
                                        provided patterns
 -C,--column-properties <arg>           define column property file
 -d,--data                              discover candidate column for
                                        anonymization based on semantic
                                        algorithms
 -D,--data-properties <arg>             discover candidate column for
                                        anonymization based on semantic
                                        algorithms
 -debug                                 enable debug output
 -F,--file discovery properties <arg>   define file discovery property
                                        file
 -h,--help                              display help
 -P,--database properties <arg>         define database property file
 -r,--requirement                       create discover and create
                                        requirement file
 -R,--requirement-file                  define requirement file name
Exception in thread "main" java.lang.NullPointerException
        at com.strider.datadefender.DataDefender.main(DataDefender.java:78)
Closing lock file

**Comment by marciahon29** [comment]
My db.properties file is as such:
vendor=mysql
driver=com.mysql.jdbc.Driver
schema=<schema>
username=<username>
password=<password>
url=jdbc:mysql://<url>:3306/<schema>
skip-empty-tables=true

**Comment by armenak** [comment]
You can't do both data and column discovery. For column discovery:
java -jar DataDefender.jar database-discovery -c
Please place your db.properties file in current directory.

**Comment by armenak** [comment]
Samples of shell and batch scripts are in https://github.com/armenak/DataDefender/tree/master/sample_projects/database_discovery.

**Comment by marciahon29** [comment]
Ahhh.. .thank you it is working now!!!

**Comment by armenak** [comment]
Thank you for letting me know.
