### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by marciahon29** [armenak/DataDefender#97]
I try the following to create a requirement file, but it does not work:

target$ /usr/local/jdk1.8.0/bin/java -jar DataDefender.jar database-discovery -d -r -R test
Creating lock file DataDefender.tmp
Locking file ...
Command-line arguments: [database-discovery, -d, -r, -R, test]
Connecting to database
Database vendor: mysql
Using driver com.mysql.jdbc.Driver
Database URL: jdbc:mysql://server:3306/<schema>
Logging in using username username
Loading database driver
Establishing database connection
Database vendor: mysql
Using driver com.mysql.jdbc.Driver
Database URL: jdbc:mysql://server:3306/<schema>
Logging in using username username
Loading database driver
Establishing database connection
Tables: [test]
Data discovery in process
Probability threshold [0.55]
Model list [[name]]
********************************
Processing model name
********************************
Fetching table names from schema <schema>
Table test
Analyzing table [test].[value1]
*** Adding list of words into array
*** Array is populated with words from dictionary
Analyzing table [test].[value2]
Analyzing table [test].[value3]
List of suspects:
              Table*              Column*         Probability*               Model*
Overall score: Undefined

Exception in thread "main" com.strider.datadefender.AnonymizerException: No matches to create requirement from!
        at com.strider.datadefender.Discoverer.createRequirement(Discoverer.java:53)
        at com.strider.datadefender.DataDefender.main(DataDefender.java:161)

**Comment by armenak** [comment]
It seems to me that you do not have tables "value1", "value2", and "value3". Can you please verify?
Also, in MySQL tables are case-sensitive.

**Comment by marciahon29** [comment]
The table name is "test". value1-value3 are the variable names in table test.

**Comment by armenak** [comment]
I have not touched this part of the code for a long time and usually was creating requirement files by myself (examples are in "sample" folder). I will look into this in next 2-3 days. Thanks for reporting the issue.

**Comment by marciahon29** [comment]
Thank you, I will look forward to your comments!

**Comment by armenak** [comment]
I've made a fix and removed -R option. Please use -r instead. The tool will generate "Sample-Requirement.xml" file based on the data discovery.

**Comment by armenak** [comment]
No response. Closing the issue.
