### ISSUE TITLE
FileDiscovery

### ISSUE THREAD

**Issue by marciahon29** [armenak/DataDefender#98]
Hello,

I'm dealing with text that contains diagnosis.

How can I create a list of diagnosis that I would like to be anonymized in the file-discovery.

For example, anorexic, bulimic, etc..

**Comment by armenak** [comment]
Unfortunately, the anonymization is working only for databases, not for files. I will consider your request as feature request.

**Comment by armenak** [comment]
For now, the results of File Discovery is for information purposes only. When I complete the file anonymization part, then it can be used similar to database anonymization.

**Comment by armenak** [comment]
>> If i were to put the text in a column, would it then be able to be anonymized?
Yes.

**Comment by marciahon29** [comment]
So this means that If I have a table with a column called "comments", and inside this column I have a record of a free-text... that I can do datadiscovery and also anonymization on this record?

**Comment by armenak** [comment]
Yes.

**Comment by armenak** [comment]
The answer is provided. This issue is a duplicate.
