### ISSUE TITLE
File Discovery Erro

### ISSUE THREAD

**Issue by marciahon29** [armenak/DataDefender#99]
I get a null pointer exception when running file discovery:

$java -jar DataDefender.jar file-discovery
Creating lock file DataDefender.tmp
Locking file ...
Command-line arguments: [file-discovery]
Data discovery in process
Probability threshold [0.5]
Model list [[generic, money, time, location, organization]]
********************************
Processing model generic
********************************
Exception in thread "main" java.lang.NullPointerException
        at com.strider.datadefender.FileDiscoverer.discoverAgainstSingleModel(FileDiscoverer.java:106)
        at com.strider.datadefender.FileDiscoverer.discover(FileDiscoverer.java:81)
        at com.strider.datadefender.DataDefender.main(DataDefender.java:103)
$ more filediscovery.properties
probability_threshold=0.5
english_tokens=en-token.bin
english_sentenses=en-sent.bin
generic=en-ner-person.bin
location=en-ner-location.bin
date=en-ner-date.bin
money=en-ner-money.bin
organization=en-ner-organization.bin
time=en-ner-time.bin
names=names.dict
limit=100
models=generic,money,time,location,organization
directories=FileDiscoveryTest

**Comment by armenak** [comment]
Please show your filediscovery.properties file.

**Comment by marciahon29** [comment]
$ more filediscovery.properties
probability_threshold=0.5
english_tokens=en-token.bin
english_sentenses=en-sent.bin
generic=en-ner-person.bin
location=en-ner-location.bin
date=en-ner-date.bin
money=en-ner-money.bin
organization=en-ner-organization.bin
time=en-ner-time.bin
names=names.dict
limit=100
models=generic,money,time,location,organization
directories=FileDiscoveryTest

**Comment by armenak** [comment]
Please use full path, such as /home/user_name/FileDiscoveryTest.

**Comment by marciahon29** [comment]
Still not working...

**Comment by armenak** [comment]
Please download new version and compile it. It should work now.
